baseURL = "https://blog.cactuserveur.fr/"  # ou ton domaine personnalisé
publishDir = "public"

languageCode = 'fr-fr'
title = 'Mon blog alala'
theme = "archie"




[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tout les posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[module]
  [[module.imports]]
    path = 'github.com/hugomods/umami-analytics'

[params]
  [params.services]
    [params.services.umami_analytics]
      id = '8261e837-91d2-433d-ba96-be0441457e4a'
      script_url = 'https://cloud.umami.is/script.js'